// Generated 15 Nov 2021 15:59 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace MELib.Orders
{
    [Serializable]
    public class DeliveyList
     : MEBusinessListBase<DeliveyList, Delivey>
    {
        #region " Business Methods "

        public Delivey GetItem(int DeliveryID)
        {
            foreach (Delivey child in this)
            {
                if (child.DeliveryID == DeliveryID)
                {
                    return child;
                }
            }
            return null;
        }

        public override string ToString()
        {
            return "Deliveys";
        }

        #endregion

        #region " Data Access "

        [Serializable]
        public class Criteria
          : CriteriaBase<Criteria>
        {
            public Criteria()
            {
            }

        }

        public static DeliveyList NewDeliveyList()
        {
            return new DeliveyList();
        }

        public DeliveyList()
        {
            // must have parameter-less constructor
        }

        public static DeliveyList GetDeliveyList()
        {
            return DataPortal.Fetch<DeliveyList>(new Criteria());
        }

        protected void Fetch(SafeDataReader sdr)
        {
            this.RaiseListChangedEvents = false;
            while (sdr.Read())
            {
                this.Add(Delivey.GetDelivey(sdr));
            }
            this.RaiseListChangedEvents = true;
        }

        protected override void DataPortal_Fetch(Object criteria)
        {
            Criteria crit = (Criteria)criteria;
            using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
            {
                cn.Open();
                try
                {
                    using (SqlCommand cm = cn.CreateCommand())
                    {
                        cm.CommandType = CommandType.StoredProcedure;
                        cm.CommandText = "GetProcs.getDeliveyList";
                        using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
                        {
                            Fetch(sdr);
                        }
                    }
                }
                finally
                {
                    cn.Close();
                }
            }
        }

        #endregion

    }

}